## 读取数据集

In [11]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [12]:
import pandas as pd
import torch

data_df = pd.read_csv(data_file)
data_df

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [13]:
# pandas太新对于字符串处理改了,新版用这个即可
inputs, outputs = data_df.iloc[:, 0:2], data_df.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
inputs

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [14]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [15]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 练习

In [16]:
# 1.练习1
import numpy as np

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny_test.csv')
rng = np.random.default_rng(42)
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    for _ in range(100):
        num_rooms = 'NA' if rng.random() < 0.15 else str(rng.integers(1, 6))
        alley = rng.choice(['Pave', 'Gravel', 'NA'], p=[0.4, 0.3, 0.3])
        price = 'NA' if rng.random() < 0.10 else str(rng.integers(50, 300) * 1000)  # 新增
        f.write(f'{num_rooms},{alley},{price}\n')

In [17]:
data_df_test = pd.read_csv(data_file)
data_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NumRooms  84 non-null     float64
 1   Alley     73 non-null     object
 2   Price     91 non-null     float64
dtypes: float64(2), object(1)
memory usage: 2.5+ KB

In [18]:
col_most_missing = data_df_test.isnull().sum().idxmax()
data_df_test = data_df_test.drop(columns=col_most_missing)
data_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NumRooms  84 non-null     float64
 1   Price     91 non-null     float64
dtypes: float64(2)
memory usage: 1.7 KB

In [19]:
# 2.练习2
ten = torch.tensor(data_df_test.to_numpy(dtype=float))
ten

tensor([[4.0000e+00, 1.5900e+05],
        [       nan, 2.2900e+05],
        [       nan, 2.4600e+05],
        [4.0000e+00, 2.1000e+05],
        [1.0000e+00, 1.8800e+05],
        [1.0000e+00, 2.3900e+05],
        [4.0000e+00, 2.4400e+05],
        [       nan, 2.8000e+05],
        [4.0000e+00, 6.9000e+04],
        [3.0000e+00, 1.3200e+05],
        [2.0000e+00, 2.0700e+05],
        [4.0000e+00, 2.6000e+05],
        [2.0000e+00, 2.5800e+05],
        [       nan, 9.9000e+04],
        [2.0000e+00, 2.4500e+05],
        [       nan, 2.1300e+05],
        [3.0000e+00, 1.9100e+05],
        [3.0000e+00,        nan],
        [5.0000e+00, 1.0300e+05],
        [5.0000e+00, 6.4000e+04],
        [1.0000e+00, 1.8900e+05],
        [3.0000e+00,        nan],
        [       nan, 2.5300e+05],
        [5.0000e+00, 1.7500e+05],
        [1.0000e+00, 1.4500e+05],
        [5.0000e+00, 7.1000e+04],
        [3.0000e+00, 2.2400e+05],
        [2.0000e+00, 2.2900e+05],
        [       nan, 2.2600e+05],
        [2.0000e+00, 1.6500e+05],
        [5.0000e+00, 1.2700e+05],
        [4.0000e+00,        nan],
        [4.0000e+00, 6.0000e+04],
        [       nan, 2.4800e+05],
        [1.0000e+00, 2.0300e+05],
        [       nan, 1.9700e+05],
        [1.0000e+00, 7.0000e+04],
        [1.0000e+00, 1.9200e+05],
        [3.0000e+00,        nan],
        [3.0000e+00, 1.2500e+05],
        [       nan, 1.8800e+05],
        [4.0000e+00, 2.3100e+05],
        [5.0000e+00, 1.0700e+05],
        [2.0000e+00, 2.5700e+05],
        [4.0000e+00, 1.2200e+05],
        [1.0000e+00, 9.1000e+04],
        [1.0000e+00, 2.7200e+05],
        [1.0000e+00, 1.7900e+05],
        [3.0000e+00, 1.4300e+05],
        [1.0000e+00, 2.8400e+05],
        [5.0000e+00, 8.8000e+04],
        [1.0000e+00, 9.9000e+04],
        [3.0000e+00,        nan],
        [3.0000e+00, 2.9200e+05],
        [1.0000e+00, 1.5400e+05],
        [1.0000e+00, 2.5600e+05],
        [       nan, 8.2000e+04],
        [1.0000e+00, 1.7200e+05],
        [5.0000e+00, 2.8100e+05],
        [5.0000e+00, 7.6000e+04],
        [1.0000e+00, 1.9900e+05],
        [4.0000e+00, 2.4600e+05],
        [2.0000e+00, 2.4900e+05],
        [5.0000e+00, 2.6600e+05],
        [5.0000e+00, 1.5600e+05],
        [3.0000e+00, 1.1100e+05],
        [5.0000e+00, 7.6000e+04],
        [       nan, 2.8000e+05],
        [1.0000e+00, 1.9400e+05],
        [       nan,        nan],
        [1.0000e+00, 1.7800e+05],
        [4.0000e+00, 2.3400e+05],
        [5.0000e+00, 2.7200e+05],
        [2.0000e+00, 1.2000e+05],
        [1.0000e+00, 7.3000e+04],
        [       nan,        nan],
        [5.0000e+00, 1.3000e+05],
        [5.0000e+00, 2.3400e+05],
        [1.0000e+00, 2.5800e+05],
        [3.0000e+00, 6.5000e+04],
        [1.0000e+00, 1.3400e+05],
        [2.0000e+00, 9.5000e+04],
        [4.0000e+00, 2.6300e+05],
        [3.0000e+00, 1.7200e+05],
        [4.0000e+00, 6.8000e+04],
        [2.0000e+00, 1.7500e+05],
        [       nan,        nan],
        [5.0000e+00, 2.3000e+05],
        [1.0000e+00, 1.6100e+05],
        [4.0000e+00, 2.3000e+05],
        [       nan, 1.9700e+05],
        [1.0000e+00, 1.9300e+05],
        [5.0000e+00, 2.4900e+05],
        [5.0000e+00,        nan],
        [1.0000e+00, 1.0200e+05],
        [4.0000e+00, 2.0800e+05],
        [2.0000e+00, 2.9000e+05],
        [1.0000e+00, 8.1000e+04],
        [4.0000e+00, 2.0300e+05],
        [3.0000e+00, 2.6100e+05]], dtype=torch.float64)